### ISSUE TITLE
As a developer, I want to be able to fetch recipes from an api.

### ISSUE THREAD

**Issue by caseycorvino** [nyu-software-engineering/limited-ingredients#3]
Acceptance Criteria:
- [ ] Learn to use JavaScript fetch()
- [ ] Find an API to use
- [ ] Learn structure of the API and fetching specifications

Estimation of work:
L

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-limited-ingredients - this and the other issues like it are labeled as both "user story" and "spike"... the two are mutually exclusive.  Spikes are internal work the team does that do not directly affect anything the user is able to do with the app.  User stories are directly related to what a user can or cannot do.  So this one is obviously a Spike.  Please update all issues to be correctly labeled.

Anything placed on the task board must also have team members assigned to it, and have Acceptance Criteria and Estimate of Work written in nice markdown syntax as sub-headings.

**Comment by ct1799** [comment]
No longer fetching recipes from an API. Closing Issue.
