### ISSUE TITLE
As a developer, I want to determine which front-end technologies to use

### ISSUE THREAD

**Issue by abdankar** [nyu-software-engineering/limited-ingredients#4]
This spike is part of user story 17.
## Acceptance Criteria
- [x] Research React
- [x] Research Node
- [ ] Research Express
- [ ] Research Mongoose
- [ ] Research MongoDB
- [ ] Research MLAB

## Estimation of work
L

**Comment by ct1799** [comment]
We've determined to use React, Facebook authentication, Node, Mongo, Mongoose, Node Package Manager, M-Lab, Express for now
