### ISSUE TITLE
Learn NodeJs

### ISSUE THREAD

**Issue by thatBrian** [nyu-software-engineering/limited-ingredients#5]
### Description
This spike is part of user story #17
### Estimation of Work
- M

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-limited-ingredients - is this really a valid acceptance criterion?!
> * running "node -v" in a terminal should return a version

**Comment by thatBrian** [comment]
> @nyu-software-engineering/spring-2019-limited-ingredients - is this really a valid acceptance criterion?!
> 
> > * running "node -v" in a terminal should return a version

No it is not. Thank you for letting us know.
